apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: dapr.db.aws.asarenkansah.com
  labels:
    type: dapr-dev
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: asarenkansah.com/v1alpha1
    kind: Database
  writeConnectionSecretsToNamespace: crossplane-system
  patchSets:
  - name: metadata
    patches:
    - fromFieldPath: metadata.labels
  resources:
  - name: CacheClusterGroup
    base:
      apiVersion: cache.aws.crossplane.io/v1beta1
      kind: ReplicationGroup
      spec:
        forProvider:
          applyModificationsImmediately: true
          cacheNodeType: "cache.t2.micro"
          numCacheClusters: 1
          replicationGroupDescription: An example replication group
          engine: "redis"
          region: us-east-1
          port: 6379
        providerConfigRef:
          name: default
        writeConnectionSecretToRef:
          namespace: crossplane-system
    patches:
    - fromFieldPath: "metadata.uid"
      toFieldPath: "spec.writeConnectionSecretToRef.name"
      transforms:
        - type: string
          string:
            fmt: "%s-redis"
  - name: redis-secret
    base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        providerConfigRef: 
          name: default
        references:
        - patchesFrom:
            apiVersion: v1
            kind: Secret
            namespace: crossplane-system
            fieldPath: data.endpoint
          toFieldPath: data.endpoint  
        forProvider:
          manifest:
            apiVersion: v1
            kind: Secret
            metadata:
              namespace: default
              name: #patched
            data:
              url: #patched
    patches:
      - fromFieldPath: metadata.name
        toFieldPath: spec.forProvider.manifest.metadata.name
        transforms:
        - type: string
          string:
            fmt: '%s-redis-dapr'   
      - fromFieldPath: metadata.uid
        toFieldPath: spec.references[0].patchesFrom.name
        transforms:
        - type: string
          string:
            fmt: '%s-redis'
      - type: CombineFromComposite
        combine:
          variables:
          - fromFieldPath: data.endpoint
          strategy: string
          string:
            fmt: "%s:6379"  
        toFieldPath: spec.forProvider.manifest.data.url  
        transforms:
        - type: string
          string:
            type: Convert
            convert: ToBase64
  - name: dapr-statestore
    base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        providerConfigRef: 
          name: default
        forProvider:
          manifest:
            apiVersion: dapr.io/v1alpha1
            kind: Component
            metadata:
              name: #patched
              namespace: default
            spec:
              type: state.redis
              version: v1
              metadata:
              - name: redisHost
                secretKeyRef:
                  name: #patched
                  key:  url
              - name: redisPassword
                value: ""
              - name: keyPrefix
                value: name
    patches:
      - fromFieldPath: metadata.name
        toFieldPath: spec.forProvider.manifest.metadata.name
        transforms:
        - type: string
          string:
            fmt: '%s-statestore'
      - fromFieldPath: metadata.name
        toFieldPath: spec.forProvider.manifest.spec.metadata[0].secretKeyRef.name
        transforms:
        - type: string
          string:
            fmt: '%s-redis-dapr'
  